---
- name: Desktop setup. 
  hosts: 127.0.0.1
  become: true
  tasks:

  - name: "Setup local desktop development."
    block:

      - name: Install apt Packages
        apt:
          name: "{{item}}"
          state: present
          update_cache: yes
        loop:
          - gnupg-agent
          - software-properties-common
          - net-tools
          - unzip
          - awscli
          - terminator
          - vim
          - gnome-tweaks
          - gnome-shell-extension*

      - name: Install pyenv
        raw: "curl https://pyenv.run | bash"
        ignore_errors: yes

      - name: Configure Pyenv
        raw: grep pyenv ~/.bashrc || (echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bashrc && echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc && echo 'eval "$(pyenv init -)"' >> ~/.bashrc && echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bashrc && exec $SHELL)
        become: no

      - name: echo1
        raw: "echo 1"

    rescue:

      - name: echo2
        raw: "echo 2"

    always:
    
      - name: echo3
        raw: "echo 3"


        