---
- name: Desktop setup. 
  hosts: 127.0.0.1
  become: true
  tasks:

  - name: "Setup local desktop development."
    block:

      - name: Install Packages
        apt:
          name: "{{item}}"
          state: present
          update_cache: yes
        loop:
          - gnupg-agent
          - software-properties-common
          - net-tools
          - unzip
          - awscli
          - terminator

      - name: echo1
        raw: "echo 1"

    rescue:

      - name: echo2
        raw: "echo 2"

    always:
    
      - name: echo3
        raw: "echo 3"